[package]
edition = "2021"
name = "mady"
version = "0.1.0"
authors = ["by EHY <https://github.com/organizations/MDResearch/> "]

[dependencies]

[workspace]
members = [
    "mady_math",
    "mady_macro",
]