[package]
edition = "2021"
name = "research"
version = "0.1.0"
bench = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mad = {path = "mad"}
ad = {path = "ad"}
fastrand = "1.5.0"
