[package]
authors = ["by EHY <https://github.com/organizations/MDResearch/> "]
edition = "2021"
name = "mady"
version = "0.1.0"

[dependencies.mady_math]
path = "./mady_math"

[dependencies.mady_macro]
path = "./mady_macro"

[dev-dependencies]
rand_distr = "0.4.3"
rand = "0.8.5"

[workspace]
members = [
  "mady_math",
  "mady_macro",
]

[features]
default = ["macro", "math"]
macro = []
math = []
