[package]
edition = "2021"
name = "mady_macro"
version = "0.1.0-beta"
description = "🌲 mady's subpackage"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[dependencies.syn]
features = ["full", "extra-traits", "fold", "parsing"]
version = "1.0"

[dependencies.mady_macro_core]
path = "./../mady_macro_core"
version = "0.1.0-alpha"

[lib]
proc-macro = true
