name: Rust Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup just
      uses: extractions/setup-just@v1
    - name: Check All
      run: just c
    - name: Build
      run: just b
    - name: Tests All
      run: just t
    - name: FMT
      run: just f
    - name: Lint
      run: just l
    - name: Commit Change
      run: |
        git config --global user.name "CI"
        git config --global user.email "ci@mady.ci"
        git add -A
        git commit -m "FMT & Autofix"
        if [ $? -eq 0 ]; then
          git push
        fi